AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bare minimum clj for lambda.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ridho-test/4b7598747be1d55c59088d6a0fa197e3
      Handler: me.explore.aws_lambda
      Runtime: java11
      Description: Java function
      MemorySize: 256
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
