version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Ridho-Test-HelloClj"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5egkxq3archm"
s3_prefix = "Ridho-Test-HelloClj"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
