AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Bare minimum clj for lambda.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-lambda-0.1.0.jar
      Handler: me.explore.aws_lambda
      Runtime: java11
      Description: Java function
      MemorySize: 256
      Timeout: 10 # seconds
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
